version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/mixcr

    environment:
      MAX_MEMORY_OVERRIDE: 3500
      MAVEN_OPTS: -Xmx3g

    steps:
      - checkout

      - run:
          name: Downloading git submodules
          command: git submodule update --init --recursive

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "milib/pom.xml" }}-{{ checksum "repseqio/pom.xml" }}
            - v1-dependencies-

      - run:
          name: Building MiLib
          working_directory: milib
          command: mvn clean install -DskipTests --batch-mode

      - restore_cache:
          keys:
            - v1-repseqio-cache-{{ checksum "repseqio/.gitmodules" }}
            - v1-repseqio-cache-

      - run:
          name: Building RepseqIO
          working_directory: repseqio
          command: mvn clean install -DskipTests --batch-mode

      - save_cache:
          paths:
            - repseqio/.cache
          key: v1-repseqio-cache-{{ checksum "repseqio/.gitmodules" }}

      - restore_cache:
          key: v1-test-data-{{ checksum "ensure-test-data.sh" }}

      - run:
          name: Downloading test data
          command: ./ensure-test-data.sh

      - save_cache:
          paths:
            - src/test/resources/sequences/big/
          key: v1-test-data-{{ checksum "ensure-test-data.sh" }}

      - run:
          name: Building and testing MiXCR
          command: mvn clean install

      - store_test_results:
          path: target/surefire-reports

      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}-{{ checksum "milib/pom.xml" }}-{{ checksum "repseqio/pom.xml" }}

      - run:
          name: Running MiXCR Integration tests
          command: ./itests.sh test
