version: 2.1
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk

    working_directory: ~/mixcr

    environment:
      MAVEN_OPTS: -Xmx1024m

    steps:
      - checkout

      - restore_cache:
          keys:
            - dependencies-{{ checksum "pom.xml" }}
            - dependencies-

      - run:
          name: Downloading git submodules
          command: |
            git submodule update --init --recursive

      - run:
          name: Building MiLib
          working_directory: milib
          command: mvn clean install -DskipTests --batch-mode

      - restore_cache:
          key: repseqio-cache

      - run:
          name: Building RepseqIO
          working_directory: repseqio
          command: mvn clean install -DskipTests --batch-mode

      - save_cache:
          paths:
            - repseqio/.cache
          key: repseqio-cache

      - restore_cache:
          key: test-data

      - run:
          name: Downloading test data
          command: ./ensure-test-data.sh

      - save_cache:
          paths:
            - src/test/resources/sequences/big/
          key: test-data

#      - run:
#          name: Building and testing MiXCR
#          command: mvn clean install

      - save_cache:
          paths:
            - ~/.m2
          key: dependencies-{{ checksum "pom.xml" }}

#      - run: mvn package && ./build.sh && ./ensure-test-data.sh && ./itests.sh test
#
#      - store_test_results:
#          path: target/surefire-reports
