flags:
  - leftAlignmentMode
  - assembleClonesBy
  - species
  - rightAlignmentMode
  - materialType
pipeline:
  - align
  - assemble
  - exportClones
align:
  species: ""
  libraryName: default
  trimmingQualityThreshold: 10
  trimmingWindowSize: 6
  chains: ALL
  replaceWildcards: true
  overlapPairedReads: true
  bamDropNonVDJ: false
  writeFailedAlignments: false
  tagPattern: null
  tagUnstranded: false
  tagMaxBudget: 10.0
  headerExtractors: []
  readIdAsCellTag: false
  sampleTable: null
  tagsValidations: []
  splitBySample: true
  limit: null
  parameters:
    vParameters:
      geneFeatureToAlign: VRegionWithP
      minSumScore: 150
      relativeMinScore: 0.97
      maxHits: 5
      parameters:
        type: kaligner2
        mapperNValue: 8
        mapperKValue: 1
        floatingLeftBound: true
        floatingRightBound: true
        mapperAbsoluteMinClusterScore: 102
        mapperExtraClusterScore: -38
        mapperMatchScore: 98
        mapperMismatchScore: -14
        mapperOffsetShiftScore: -82
        mapperSlotCount: 8
        mapperMaxClusters: 11
        mapperMaxClusterIndels: 4
        mapperKMersPerPosition: 4
        mapperAbsoluteMinScore: 103
        mapperRelativeMinScore: 0.81
        mapperMinSeedsDistance: 8
        mapperMaxSeedsDistance: 8
        alignmentStopPenalty: 0
        absoluteMinScore: 150
        relativeMinScore: 0.8
        maxHits: 2
        scoring:
          type: affine
          alphabet: nucleotide
          subsMatrix: "simple(match = 10, mismatch = -19)"
          gapOpenPenalty: -62
          gapExtensionPenalty: -11
    dParameters:
      geneFeatureToAlign: DRegionWithP
      relativeMinScore: 0.85
      absoluteMinScore: 25.0
      maxHits: 3
      scoring:
        type: linear
        alphabet: nucleotide
        subsMatrix: "simple(match = 5, mismatch = -9)"
        gapPenalty: -12
    jParameters:
      geneFeatureToAlign: JRegionWithP
      minSumScore: 150
      relativeMinScore: 0.97
      maxHits: 5
      parameters:
        type: kaligner2
        mapperNValue: 8
        mapperKValue: 1
        floatingLeftBound: true
        floatingRightBound: false
        mapperAbsoluteMinClusterScore: 102
        mapperExtraClusterScore: -38
        mapperMatchScore: 95
        mapperMismatchScore: -14
        mapperOffsetShiftScore: -82
        mapperSlotCount: 6
        mapperMaxClusters: 4
        mapperMaxClusterIndels: 4
        mapperKMersPerPosition: 4
        mapperAbsoluteMinScore: 100
        mapperRelativeMinScore: 0.8
        mapperMinSeedsDistance: 5
        mapperMaxSeedsDistance: 5
        alignmentStopPenalty: 0
        absoluteMinScore: 150
        relativeMinScore: 0.8
        maxHits: 3
        scoring:
          type: affine
          alphabet: nucleotide
          subsMatrix: "simple(match = 10, mismatch = -19)"
          gapOpenPenalty: -62
          gapExtensionPenalty: -11
    cParameters:
      geneFeatureToAlign: CExon1
      minSumScore: 40
      relativeMinScore: 0.97
      maxHits: 5
      parameters:
        type: kaligner
        mapperKValue: 5
        floatingLeftBound: false
        floatingRightBound: false
        mapperAbsoluteMinScore: 1.5
        mapperRelativeMinScore: 0.75
        mapperMatchScore: 1.0
        mapperMismatchPenalty: -0.1
        mapperOffsetShiftPenalty: -0.3
        mapperMinSeedsDistance: 4
        mapperMaxSeedsDistance: 10
        minAlignmentLength: 15
        maxAdjacentIndels: 2
        alignmentStopPenalty: -1000
        absoluteMinScore: 40.0
        relativeMinScore: 0.87
        maxHits: 7
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -9)"
          gapPenalty: -12
    vjAlignmentOrder: VThenJ
    libraryStructure: Unknown
    includeDScore: false
    includeCScore: false
    minSumScore: 120.0
    relativeMinVFR3CDR3Score: 0.7
    allowPartialAlignments: false
    allowNoCDR3PartAlignments: false
    allowChimeras: false
    readsLayout: Opposite
    mergerParameters:
      qualityMergingAlgorithm: MaxSubtraction
      partsLayout: null
      minimalOverlap: 13
      minimalMatchQualitySum: 364
      maxQuality: 50
      minimalIdentity: 0.7
      identityType: MinimalQualityWeighted
    fixSeed: true
    alignmentBoundaryTolerance: 5
    minChimeraDetectionScore: 120
    vjOverlapWindow: 3
    saveOriginalSequence: false
    saveOriginalReads: false
    smartForceEdgeAlignments: true
    retriesForPartialAlignments: 3
refineTagsAndSort:
  whitelists: {}
  runCorrection: true
  parameters:
    correctionPower: 0.001
    backgroundSubstitutionRate: 0.001
    backgroundIndelRate: 1.0E-5
    minQuality: 12
    maxSubstitutions: 2
    maxIndels: 2
    maxTotalErrors: 3
    postFilter: null
assemblePartial:
  overlappedOnly: false
  dropPartial: false
  cellLevel: false
  parameters:
    kValue: 12
    kOffset: -7
    minimalAssembleOverlap: 12
    minimalNOverlap: 7
    minimalNOverlapShare: 0.65
    minimalAlignmentMergeIdentity: 0.85
    mergerParameters:
      qualityMergingAlgorithm: SumSubtraction
      partsLayout: CollinearDirect
      minimalOverlap: 20
      minimalMatchQualitySum: 0
      maxQuality: 45
      minimalIdentity: 0.95
      identityType: Unweighted
    maxLeftParts: 256000
    maxLeftMatches: 6144
extend:
  vAnchor: CDR3Begin
  jAnchor: FR4Begin
  minimalVScore: 50
  minimalJScore: 50
assemble:
  sortBySequence: false
  clnaOutput: false
  cellLevel: false
  consensusAssemblerParameters: null
  cloneAssemblerParameters:
    assemblingFeatures: null
    minimalClonalSequenceLength: 12
    qualityAggregationType: BetaScore
    cloneClusteringParameters:
      searchDepth: 2
      allowedMutationsInNRegions: 1
      searchParameters: twoMismatchesOrIndels
      clusteringFilter:
        type: advanced
        correctionPower: 0.001
        backgroundSubstitutionRate: 0.002
        backgroundIndelRate: 2.0E-4
    cloneFactoryParameters:
      vParameters:
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      jParameters:
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      cParameters:
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      dParameters:
        relativeMinScore: null
        absoluteMinScore: null
        maxHits: null
        scoring: null
    separateByV: false
    separateByJ: false
    separateByC: false
    maximalPreClusteringRatio: 1.0
    preClusteringScoreFilteringRatio: 2.0
    preClusteringCountFilteringRatio: 2.0
    addReadsCountOnClustering: false
    badQualityThreshold: 15
    maxBadPointsPercent: 0.7
    mappingThreshold: 2of5
    minimalQuality: 20
    postFilters: null
  inferMinRecordsPerConsensus: false
assembleContigs:
  ignoreTags: false
  parameters:
    branchingMinimalQualityShare: 0.1
    branchingMinimalSumQuality: 60
    decisiveBranchingSumQualityThreshold: 120
    alignedSequenceEdgeDelta: 3
    alignmentEdgeRegionSize: 7
    minimalNonEdgePointsFraction: 0.25
    minimalMeanNormalizedQuality: 5.0
    outputMinimalQualityShare: 0.75
    outputMinimalSumQuality: 0
    subCloningRegions: null
    assemblingRegions: null
    postFiltering:
      type: NoFiltering
    trimmingParameters:
      averageQualityThreshold: 10.0
      windowSize: 8
    minimalContigLength: 20
    alignedRegionsOnly: false
    discardAmbiguousNucleotideCalls: false
  cloneFactoryParameters:
    vParameters:
      relativeMinScore: 0.97
      maxAlignmentWidthLinear: 5
      maxAlignmentWidthAffine: 500
    jParameters:
      maxAlignmentWidthLinear: 5
      maxAlignmentWidthAffine: 500
    cParameters:
      maxAlignmentWidthLinear: 5
      maxAlignmentWidthAffine: 500
    dParameters:
      relativeMinScore: null
      absoluteMinScore: null
      maxHits: null
      scoring: null
exportAlignments:
  chains: ALL
  noHeader: false
  fields:
    - field: -readIds
    - field: -targetSequences
    - field: -targetQualities
    - field: -vHitsWithScore
    - field: -dHitsWithScore
    - field: -jHitsWithScore
    - field: -cHitsWithScore
    - field: -vAlignments
    - field: -dAlignments
    - field: -jAlignments
    - field: -cAlignments
    - field: -allNFeaturesWithMinQuality
    - field: -allAAFeatures
    - field: -defaultAnchorPoints
    - field: -topChains
exportClones:
  splitByTagType: null
  filterOutOfFrames: false
  filterStops: false
  chains: ALL
  noHeader: false
  fields:
    - field: -cloneId
    - field: -readCount
    - field: -readFraction
    - field: -targetSequences
    - field: -targetQualities
    - field: -vHitsWithScore
    - field: -dHitsWithScore
    - field: -jHitsWithScore
    - field: -cHitsWithScore
    - field: -vAlignments
    - field: -dAlignments
    - field: -jAlignments
    - field: -cAlignments
    - field: -allNFeaturesWithMinQuality
    - field: -allAAFeatures
    - field: -defaultAnchorPoints
  splitFilesBy:
    - chain
  groupClonesBy: []
qc:
  checks:
    - type: SuccessfullyAlignedReads
      upper: 0.85
      middle: 0.7
      label: Successfully aligned reads
    - type: OffTargetReads
      upper: 0.2
      middle: 0.1
      label: Off target (non TCR/IG) reads
    - type: ReadsWithNoVOrJHits
      upper: 0.2
      middle: 0.1
      label: Reads with no V or J hits
    - type: ReadsUsedInClonotypes
      upper: 0.9
      middle: 0.7
      label: Reads used in clonotypes
    - type: AlignmentsWithNoAssemblingFeature
      upper: 0.15
      middle: 0.05
      label: Alignments without assembling feature
    - type: AlignmentsDroppedLowQuality
      upper: 0.05
      middle: 0.01
      label: Alignments dropped due to low sequence quality
    - type: ClonesDroppedInPostFiltering
      upper: 0.05
      middle: 0.01
      label: Clones dropped in post-filtering
    - type: AlignmentsDroppedInPostFiltering
      upper: 0.05
      middle: 0.01
      label: Alignments dropped in clones post-filtering
