flags:
- species
pipeline:
- align
- refineTagsAndSort
- assemble
- exportClones
align:
  species: ""
  libraryName: default
  trimmingQualityThreshold: 10
  trimmingWindowSize: 6
  chains: ALL
  replaceWildcards: true
  overlapPairedReads: true
  bamDropNonVDJ: false
  writeFailedAlignments: false
  tagPattern: |
    ^NN(CELL3PLATE:N{5})ga(CELL1ROW:N{5})ccagggttttcccagtcacgac(R1:*) \
    ^NN(CELL2COLUMN:N{5})gtcactggatttagagtctctcag(R2:*) |
    ^NN(CELL2COLUMN:N{5})gagatctctgcttctgatggctc(R2:*)
  tagUnstranded: false
  tagMaxBudget: 10.0
  readIdAsCellTag: false
  sampleTable: null
  tagsValidations:
  - type: MustNotContainTagType
    tagType: Sample
  splitBySample: false
  limit: null
  parameters:
    vParameters:
      geneFeatureToAlign: VTranscriptWithP
      minSumScore: 150
      relativeMinScore: 0.97
      parameters:
        type: kaligner2
        mapperNValue: 8
        mapperKValue: 1
        floatingLeftBound: false
        floatingRightBound: true
        mapperAbsoluteMinClusterScore: 102
        mapperExtraClusterScore: -38
        mapperMatchScore: 98
        mapperMismatchScore: -14
        mapperOffsetShiftScore: -82
        mapperSlotCount: 8
        mapperMaxClusters: 11
        mapperMaxClusterIndels: 4
        mapperKMersPerPosition: 4
        mapperAbsoluteMinScore: 103
        mapperRelativeMinScore: 0.81
        mapperMinSeedsDistance: 8
        mapperMaxSeedsDistance: 8
        alignmentStopPenalty: 0
        absoluteMinScore: 150
        relativeMinScore: 0.8
        maxHits: 2
        scoring:
          type: affine
          alphabet: nucleotide
          subsMatrix: "simple(match = 10, mismatch = -19)"
          gapOpenPenalty: -62
          gapExtensionPenalty: -11
    dParameters:
      geneFeatureToAlign: DRegionWithP
      relativeMinScore: 0.85
      absoluteMinScore: 25.0
      maxHits: 3
      scoring:
        type: linear
        alphabet: nucleotide
        subsMatrix: "simple(match = 5, mismatch = -9)"
        gapPenalty: -12
    jParameters:
      geneFeatureToAlign: JRegionWithP
      minSumScore: 150
      relativeMinScore: 0.97
      parameters:
        type: kaligner2
        mapperNValue: 8
        mapperKValue: 1
        floatingLeftBound: true
        floatingRightBound: false
        mapperAbsoluteMinClusterScore: 102
        mapperExtraClusterScore: -38
        mapperMatchScore: 95
        mapperMismatchScore: -14
        mapperOffsetShiftScore: -82
        mapperSlotCount: 6
        mapperMaxClusters: 4
        mapperMaxClusterIndels: 4
        mapperKMersPerPosition: 4
        mapperAbsoluteMinScore: 100
        mapperRelativeMinScore: 0.8
        mapperMinSeedsDistance: 5
        mapperMaxSeedsDistance: 5
        alignmentStopPenalty: 0
        absoluteMinScore: 150
        relativeMinScore: 0.8
        maxHits: 3
        scoring:
          type: affine
          alphabet: nucleotide
          subsMatrix: "simple(match = 10, mismatch = -19)"
          gapOpenPenalty: -62
          gapExtensionPenalty: -11
    cParameters:
      geneFeatureToAlign: CExon1
      minSumScore: 40
      relativeMinScore: 0.97
      parameters:
        type: kaligner
        mapperKValue: 5
        floatingLeftBound: false
        floatingRightBound: false
        mapperAbsoluteMinScore: 1.5
        mapperRelativeMinScore: 0.75
        mapperMatchScore: 1.0
        mapperMismatchPenalty: -0.1
        mapperOffsetShiftPenalty: -0.3
        mapperMinSeedsDistance: 4
        mapperMaxSeedsDistance: 10
        minAlignmentLength: 15
        maxAdjacentIndels: 2
        alignmentStopPenalty: -1000
        absoluteMinScore: 40.0
        relativeMinScore: 0.87
        maxHits: 7
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -9)"
          gapPenalty: -12
    vjAlignmentOrder: VThenJ
    libraryStructure: Unknown
    includeDScore: false
    includeCScore: false
    minSumScore: 120.0
    maxHits: 5
    relativeMinVFR3CDR3Score: 0.7
    allowPartialAlignments: false
    allowNoCDR3PartAlignments: false
    allowChimeras: false
    readsLayout: Opposite
    mergerParameters:
      qualityMergingAlgorithm: MaxSubtraction
      partsLayout: null
      minimalOverlap: 13
      minimalMatchQualitySum: 364
      maxQuality: 50
      minimalIdentity: 0.7
      identityType: MinimalQualityWeighted
    fixSeed: true
    alignmentBoundaryTolerance: 5
    minChimeraDetectionScore: 120
    vjOverlapWindow: 3
    saveOriginalSequence: false
    saveOriginalReads: false
    smartForceEdgeAlignments: true
refineTagsAndSort:
  whitelists:
    CELL1ROW: builtin:han-2014-cell1-row
    CELL2COLUMN: builtin:han-2014-cell2-column
    CELL3PLATE: builtin:han-2014-cell3-plate
  runCorrection: true
  parameters:
    correctionPower: 0.001
    backgroundSubstitutionRate: 0.001
    backgroundIndelRate: 1.0E-5
    minQuality: 12
    maxSubstitutions: 2
    maxIndels: 0
    maxTotalErrors: 3
    postFilter:
      type: filter_groups
      groupingKeys:
      - allTags:Cell
      predicates:
      - metrics:
        - type: group_metric_sum_weight
          reportHist:
            log: true
            binNumber: 0
            minBinWidth: 0.2
            multiplyWeightByKey: false
        operator:
          type: group_operator_cumtop
          share: 0.99
          accept: High
        expectedSorting: []
        requiredSequences: []
      expectedSorting:
      - allTags:Cell
      requiredSequences: []
assemblePartial:
  overlappedOnly: false
  dropPartial: false
  cellLevel: false
  parameters:
    kValue: 12
    kOffset: -7
    minimalAssembleOverlap: 12
    minimalNOverlap: 7
    minimalNOverlapShare: 0.65
    minimalAlignmentMergeIdentity: 0.85
    mergerParameters:
      qualityMergingAlgorithm: SumSubtraction
      partsLayout: CollinearDirect
      minimalOverlap: 20
      minimalMatchQualitySum: 0
      maxQuality: 45
      minimalIdentity: 0.95
      identityType: Unweighted
    maxLeftParts: 256000
    maxLeftMatches: 6144
extend:
  vAnchor: CDR3Begin
  jAnchor: FR4Begin
  minimalVScore: 50
  minimalJScore: 50
assemble:
  sortBySequence: false
  clnaOutput: false
  cellLevel: false
  consensusAssemblerParameters:
    assembler:
      aAssemblerParameters:
        bandWidth: 4
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -4)"
          gapPenalty: -14
        minAlignmentScore: 40
        maxNormalizedAlignmentPenalty: 0.15
        trimMinimalSumQuality: 0
        trimReferenceRegion: false
        maxQuality: 45
      maxIterations: 6
      minAltSeedQualityScore: 11
      minAltSeedNormalizedPenalty: 0.35
      altSeedPenaltyTolerance: 0.3
      minRecordSharePerConsensus: 0.05
      minRecordsPerConsensus: 0
      minRecursiveRecordShare: 0.3
      minQualityScore: 0
      maxConsensuses: 5
    minTagSuffixShare: 0.0
  cloneAssemblerParameters:
    assemblingFeatures:
    - CDR3
    minimalClonalSequenceLength: 12
    qualityAggregationType: BetaScore
    cloneClusteringParameters:
      searchDepth: 2
      allowedMutationsInNRegions: 1
      searchParameters: twoMismatchesOrIndels
      clusteringFilter:
        type: advanced
        correctionPower: 0.001
        backgroundSubstitutionRate: 5.0E-4
        backgroundIndelRate: 2.0E-4
    cloneFactoryParameters:
      vParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      jParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      cParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      dParameters:
        relativeMinScore: null
        absoluteMinScore: null
        maxHits: null
        scoring: null
    separateByV: false
    separateByJ: false
    separateByC: false
    maximalPreClusteringRatio: 1.0
    preClusteringScoreFilteringRatio: 2.0
    preClusteringCountFilteringRatio: 2.0
    addReadsCountOnClustering: false
    badQualityThreshold: 15
    maxBadPointsPercent: 0.7
    mappingThreshold: 2of5
    minimalQuality: 20
    postFilters:
    - type: filter_in_groups
      isolationKeys:
      - allTags:Cell
      nestedFilter:
        type: filter_groups
        groupingKeys:
        - clone
        predicates:
        - metrics:
          - type: group_metric_sum_weight
            reportHist:
              log: true
              binNumber: 0
              minBinWidth: 0.1
              multiplyWeightByKey: false
          operator:
            type: group_operator_cumtop
            share: 0.99
            accept: High
          expectedSorting: []
          requiredSequences: []
        expectedSorting:
        - clone
        requiredSequences: []
      aggregateReport: true
      expectedSorting:
      - allTags:Cell
      - clone
  inferMinRecordsPerConsensus: true
assembleContigs:
  ignoreTags: false
  parameters:
    branchingMinimalQualityShare: 0.1
    branchingMinimalSumQuality: 60
    decisiveBranchingSumQualityThreshold: 120
    alignedSequenceEdgeDelta: 3
    alignmentEdgeRegionSize: 7
    minimalNonEdgePointsFraction: 0.25
    minimalMeanNormalizedQuality: 5.0
    outputMinimalQualityShare: 0.75
    outputMinimalSumQuality: 0
    subCloningRegions: null
    assemblingRegions: null
    postFiltering:
      type: NoFiltering
    trimmingParameters:
      averageQualityThreshold: 10.0
      windowSize: 8
    minimalContigLength: 20
    alignedRegionsOnly: false
    discardAmbiguousNucleotideCalls: false
exportAlignments:
  chains: ALL
  noHeader: false
  fields:
  - field: -readIds
  - field: -targetSequences
  - field: -targetQualities
  - field: -vHitsWithScore
  - field: -dHitsWithScore
  - field: -jHitsWithScore
  - field: -cHitsWithScore
  - field: -vAlignments
  - field: -dAlignments
  - field: -jAlignments
  - field: -cAlignments
  - field: -allNFeaturesWithMinQuality
  - field: -allAAFeatures
  - field: -defaultAnchorPoints
exportClones:
  splitByTagType: null
  filterOutOfFrames: false
  filterStops: false
  chains: ALL
  noHeader: false
  fields:
  - field: -cloneId
  - field: -tags
    args:
    - Cell
  - field: -readCount
  - field: -targetSequences
  - field: -targetQualities
  - field: -vHitsWithScore
  - field: -dHitsWithScore
  - field: -jHitsWithScore
  - field: -cHitsWithScore
  - field: -vAlignments
  - field: -dAlignments
  - field: -jAlignments
  - field: -cAlignments
  - field: -nFeature
    args:
    - FR1
  - field: -minFeatureQuality
    args:
    - FR1
  - field: -nFeature
    args:
    - CDR1
  - field: -minFeatureQuality
    args:
    - CDR1
  - field: -nFeature
    args:
    - FR2
  - field: -minFeatureQuality
    args:
    - FR2
  - field: -nFeature
    args:
    - CDR2
  - field: -minFeatureQuality
    args:
    - CDR2
  - field: -nFeature
    args:
    - FR3
  - field: -minFeatureQuality
    args:
    - FR3
  - field: -nFeature
    args:
    - CDR3
  - field: -minFeatureQuality
    args:
    - CDR3
  - field: -nFeature
    args:
    - FR4
  - field: -minFeatureQuality
    args:
    - FR4
  - field: -aaFeature
    args:
    - FR1
  - field: -aaFeature
    args:
    - CDR1
  - field: -aaFeature
    args:
    - FR2
  - field: -aaFeature
    args:
    - CDR2
  - field: -aaFeature
    args:
    - FR3
  - field: -aaFeature
    args:
    - CDR3
  - field: -aaFeature
    args:
    - FR4
  - field: -defaultAnchorPoints
  splitFilesBy: []
  groupClonesBy: []
qc:
  checks:
  - type: SuccessfullyAlignedReads
    upper: 0.85
    middle: 0.7
    label: Successfully aligned reads
  - type: OffTargetReads
    upper: 0.2
    middle: 0.1
    label: Off target (non TCR/IG) reads
  - type: ReadsWithNoVOrJHits
    upper: 0.2
    middle: 0.1
    label: Reads with no V or J hits
  - type: ReadsUsedInClonotypes
    upper: 0.9
    middle: 0.7
    label: Reads used in clonotypes
  - type: AlignmentsWithNoAssemblingFeature
    upper: 0.15
    middle: 0.05
    label: Alignments without assembling feature
  - type: AlignmentsDroppedLowQuality
    upper: 0.05
    middle: 0.01
    label: Alignments dropped due to low sequence quality
  - type: AlignmentsClusteredInAssembler
    upper: 0.05
    middle: 0.01
    label: Alignments clustered in PCR error correction
  - type: ClonesClusteredInAssembler
    upper: 0.05
    middle: 0.01
    label: Clonotypes clustered in PCR error correction
  - type: ClonesDroppedInPostFiltering
    upper: 0.05
    middle: 0.01
    label: Clones dropped in post-filtering
  - type: AlignmentsDroppedInPostFiltering
    upper: 0.05
    middle: 0.01
    label: Alignments dropped in clones post-filtering
