flags: []
pipeline:
- align
- refineTagsAndSort
- assemble
- exportClones
align:
  species: hs
  libraryName: default
  trimmingQualityThreshold: 10
  trimmingWindowSize: 6
  chains: ALL
  replaceWildcards: true
  overlapPairedReads: true
  bamDropNonVDJ: false
  writeFailedAlignments: false
  tagPattern: "^(CELL1:N{8})N{16}(CELL2:N{8})N{16}(CELL3:N{8})N(UMI:N{8})N{18}(R1:*)\\\
    ^(R2:*)"
  tagUnstranded: false
  tagMaxBudget: 10.0
  readIdAsCellTag: false
  sampleTable: null
  splitBySample: false
  limit: null
  parameters:
    vParameters:
      geneFeatureToAlign: VTranscriptWithP
      minSumScore: 80
      relativeMinScore: 0.97
      parameters:
        type: kaligner
        mapperKValue: 5
        floatingLeftBound: true
        floatingRightBound: true
        mapperAbsoluteMinScore: 1.5
        mapperRelativeMinScore: 0.7
        mapperMatchScore: 1.0
        mapperMismatchPenalty: -0.1
        mapperOffsetShiftPenalty: -0.3
        mapperMinSeedsDistance: 4
        mapperMaxSeedsDistance: 10
        minAlignmentLength: 15
        maxAdjacentIndels: 2
        alignmentStopPenalty: -1000
        absoluteMinScore: 55.0
        relativeMinScore: 0.87
        maxHits: 7
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -11)"
          gapPenalty: -21
    dParameters:
      geneFeatureToAlign: DRegionWithP
      relativeMinScore: 0.85
      absoluteMinScore: 25.0
      maxHits: 3
      scoring:
        type: linear
        alphabet: nucleotide
        subsMatrix: "simple(match = 5, mismatch = -11)"
        gapPenalty: -21
    jParameters:
      geneFeatureToAlign: JRegionWithP
      minSumScore: 60
      relativeMinScore: 0.97
      parameters:
        type: kaligner
        mapperKValue: 5
        floatingLeftBound: true
        floatingRightBound: true
        mapperAbsoluteMinScore: 1.5
        mapperRelativeMinScore: 0.75
        mapperMatchScore: 1.0
        mapperMismatchPenalty: -0.1
        mapperOffsetShiftPenalty: -0.3
        mapperMinSeedsDistance: 4
        mapperMaxSeedsDistance: 8
        minAlignmentLength: 15
        maxAdjacentIndels: 2
        alignmentStopPenalty: -1000
        absoluteMinScore: 50.0
        relativeMinScore: 0.87
        maxHits: 7
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -11)"
          gapPenalty: -21
    cParameters:
      geneFeatureToAlign: CExon1
      minSumScore: 40
      relativeMinScore: 0.97
      parameters:
        type: kaligner
        mapperKValue: 5
        floatingLeftBound: false
        floatingRightBound: true
        mapperAbsoluteMinScore: 1.5
        mapperRelativeMinScore: 0.75
        mapperMatchScore: 1.0
        mapperMismatchPenalty: -0.1
        mapperOffsetShiftPenalty: -0.3
        mapperMinSeedsDistance: 4
        mapperMaxSeedsDistance: 10
        minAlignmentLength: 15
        maxAdjacentIndels: 2
        alignmentStopPenalty: -1000
        absoluteMinScore: 40.0
        relativeMinScore: 0.87
        maxHits: 7
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -11)"
          gapPenalty: -21
    vjAlignmentOrder: VThenJ
    libraryStructure: Unknown
    includeDScore: true
    includeCScore: true
    minSumScore: 200.0
    maxHits: 5
    relativeMinVFR3CDR3Score: 0.7
    allowPartialAlignments: false
    allowNoCDR3PartAlignments: false
    allowChimeras: false
    readsLayout: Opposite
    mergerParameters:
      qualityMergingAlgorithm: MaxSubtraction
      partsLayout: null
      minimalOverlap: 13
      minimalMatchQualitySum: 364
      maxQuality: 50
      minimalIdentity: 0.7
      identityType: MinimalQualityWeighted
    fixSeed: true
    alignmentBoundaryTolerance: 5
    minChimeraDetectionScore: 120
    vjOverlapWindow: 3
    saveOriginalSequence: false
    saveOriginalReads: false
    smartForceEdgeAlignments: true
refineTagsAndSort:
  whitelists:
    CELL1: builtin:singleron-whitelist
    CELL2: builtin:singleron-whitelist
    CELL3: builtin:singleron-whitelist
  runCorrection: true
  parameters:
    correctionPower: 0.001
    backgroundSubstitutionRate: 0.001
    backgroundIndelRate: 1.0E-5
    minQuality: 12
    maxSubstitutions: 2
    maxIndels: 2
    maxTotalErrors: 3
    postFilter:
      type: filter_and
      operands:
      - type: filter_groups
        groupingKeys:
        - allTags:Cell
        - allTags:Molecule
        predicates:
        - metrics:
          - type: group_metric_sum_weight
            reportHist:
              log: true
              binNumber: 0
              minBinWidth: 0.2
              multiplyWeightByKey: false
          operator:
            type: group_operator_lowest_threshold
            operators:
            - type: group_operator_advanced_thresholding
              algo:
                type: otsu
              histTransformers:
              - type: inflate
                fraction: 0.15
                value: 1.0
              logX: true
              minimalSample: 20
              fallbackThreshold: 1.0
              accept: High
            - type: group_operator_cumtop
              share: 0.95
              round: Down
              accept: High
            accept: High
          expectedSorting: []
          requiredSequences: []
        expectedSorting:
        - allTags:Cell
        - allTags:Molecule
        requiredSequences: []
      expectedSorting:
      - allTags:Cell
      - allTags:Molecule
      requiredSequences: []
assemblePartial: null
extend: null
assemble:
  sortBySequence: false
  clnaOutput: false
  cellLevel: false
  consensusAssemblerParameters:
    assembler:
      aAssemblerParameters:
        bandWidth: 4
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -4)"
          gapPenalty: -14
        minAlignmentScore: 40
        maxNormalizedAlignmentPenalty: 0.15
        trimMinimalSumQuality: 0
        trimReferenceRegion: false
        maxQuality: 45
      maxIterations: 6
      minAltSeedQualityScore: 11
      minAltSeedNormalizedPenalty: 0.35
      altSeedPenaltyTolerance: 0.3
      minRecordSharePerConsensus: 0.2
      minRecordsPerConsensus: 0
      minRecursiveRecordShare: 0.4
      minQualityScore: 0
      maxConsensuses: 3
    minTagSuffixShare: 0.0
  cloneAssemblerParameters:
    assemblingFeatures:
    - CDR3
    minimalClonalSequenceLength: 12
    qualityAggregationType: BetaScore
    cloneClusteringParameters:
      searchDepth: 2
      allowedMutationsInNRegions: 1
      searchParameters: twoMismatchesOrIndels
      clusteringFilter:
        type: advanced
        correctionPower: 0.001
        backgroundSubstitutionRate: 5.0E-4
        backgroundIndelRate: 2.0E-4
    cloneFactoryParameters:
      vParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      jParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      cParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      dParameters:
        relativeMinScore: null
        absoluteMinScore: null
        maxHits: null
        scoring: null
      vdcParameters:
        Variable:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
        Joining:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
        Constant:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
    separateByV: false
    separateByJ: false
    separateByC: false
    maximalPreClusteringRatio: 1.0
    preClusteringScoreFilteringRatio: 2.0
    preClusteringCountFilteringRatio: 2.0
    addReadsCountOnClustering: false
    badQualityThreshold: 15
    maxBadPointsPercent: 0.7
    mappingThreshold: 2of5
    minimalQuality: 21
    postFilters: null
  inferMinRecordsPerConsensus: false
assembleContigs: null
exportAlignments: null
exportClones:
  splitByTagType: null
  filterOutOfFrames: false
  filterStops: false
  chains: ALL
  noHeader: false
  fields:
  - field: -cloneId
  - field: -tags
    args:
    - Cell
  - field: -readCount
  - field: -uniqueTagCount
    args:
    - Molecule
  - field: -targetSequences
  - field: -targetQualities
  - field: -vHitsWithScore
  - field: -dHitsWithScore
  - field: -jHitsWithScore
  - field: -cHitsWithScore
  - field: -vAlignments
  - field: -dAlignments
  - field: -jAlignments
  - field: -cAlignments
  - field: -nFeature
    args:
    - FR1
  - field: -minFeatureQuality
    args:
    - FR1
  - field: -nFeature
    args:
    - CDR1
  - field: -minFeatureQuality
    args:
    - CDR1
  - field: -nFeature
    args:
    - FR2
  - field: -minFeatureQuality
    args:
    - FR2
  - field: -nFeature
    args:
    - CDR2
  - field: -minFeatureQuality
    args:
    - CDR2
  - field: -nFeature
    args:
    - FR3
  - field: -minFeatureQuality
    args:
    - FR3
  - field: -nFeature
    args:
    - CDR3
  - field: -minFeatureQuality
    args:
    - CDR3
  - field: -nFeature
    args:
    - FR4
  - field: -minFeatureQuality
    args:
    - FR4
  - field: -aaFeature
    args:
    - FR1
  - field: -aaFeature
    args:
    - CDR1
  - field: -aaFeature
    args:
    - FR2
  - field: -aaFeature
    args:
    - CDR2
  - field: -aaFeature
    args:
    - FR3
  - field: -aaFeature
    args:
    - CDR3
  - field: -aaFeature
    args:
    - FR4
  - field: -defaultAnchorPoints
  splitFilesBy: []
  groupClonesBy: []
