flags: []
pipeline:
- align
- refineTagsAndSort
- assemble
- exportClones
validation:
- type: TagPatternShouldContainsTagName
  tagName: UMI
align:
  species: hs
  libraryName: default
  trimmingQualityThreshold: 10
  trimmingWindowSize: 6
  chains: ALL
  replaceWildcards: true
  overlapPairedReads: true
  bamDropNonVDJ: false
  writeFailedAlignments: false
  tagPattern: "^N{7}(R1:*) \\ ^(UMI:N{12})N{10}(R2:*)"
  tagUnstranded: false
  tagMaxBudget: 10.0
  readIdAsCellTag: false
  tagTransformationSteps: []
  sampleTable: null
  splitBySample: false
  limit: null
  parameters:
    vParameters:
      geneFeatureToAlign: VTranscriptWithP
      minSumScore: 150
      relativeMinScore: 0.97
      parameters:
        type: kaligner2
        mapperNValue: 8
        mapperKValue: 1
        floatingLeftBound: false
        floatingRightBound: true
        mapperAbsoluteMinClusterScore: 102
        mapperExtraClusterScore: -38
        mapperMatchScore: 98
        mapperMismatchScore: -14
        mapperOffsetShiftScore: -82
        mapperSlotCount: 8
        mapperMaxClusters: 11
        mapperMaxClusterIndels: 4
        mapperKMersPerPosition: 4
        mapperAbsoluteMinScore: 103
        mapperRelativeMinScore: 0.81
        mapperMinSeedsDistance: 8
        mapperMaxSeedsDistance: 8
        alignmentStopPenalty: 0
        absoluteMinScore: 150
        relativeMinScore: 0.8
        maxHits: 2
        scoring:
          type: affine
          alphabet: nucleotide
          subsMatrix: "simple(match = 10, mismatch = -19)"
          gapOpenPenalty: -62
          gapExtensionPenalty: -11
    dParameters:
      geneFeatureToAlign: DRegionWithP
      relativeMinScore: 0.85
      absoluteMinScore: 25.0
      maxHits: 3
      scoring:
        type: linear
        alphabet: nucleotide
        subsMatrix: "simple(match = 5, mismatch = -9)"
        gapPenalty: -12
    jParameters:
      geneFeatureToAlign: JRegionWithP
      minSumScore: 150
      relativeMinScore: 0.97
      parameters:
        type: kaligner2
        mapperNValue: 8
        mapperKValue: 1
        floatingLeftBound: true
        floatingRightBound: false
        mapperAbsoluteMinClusterScore: 102
        mapperExtraClusterScore: -38
        mapperMatchScore: 95
        mapperMismatchScore: -14
        mapperOffsetShiftScore: -82
        mapperSlotCount: 6
        mapperMaxClusters: 4
        mapperMaxClusterIndels: 4
        mapperKMersPerPosition: 4
        mapperAbsoluteMinScore: 100
        mapperRelativeMinScore: 0.8
        mapperMinSeedsDistance: 5
        mapperMaxSeedsDistance: 5
        alignmentStopPenalty: 0
        absoluteMinScore: 150
        relativeMinScore: 0.8
        maxHits: 3
        scoring:
          type: affine
          alphabet: nucleotide
          subsMatrix: "simple(match = 10, mismatch = -19)"
          gapOpenPenalty: -62
          gapExtensionPenalty: -11
    cParameters:
      geneFeatureToAlign: CExon1
      minSumScore: 40
      relativeMinScore: 0.97
      parameters:
        type: kaligner
        mapperKValue: 5
        floatingLeftBound: false
        floatingRightBound: true
        mapperAbsoluteMinScore: 1.5
        mapperRelativeMinScore: 0.75
        mapperMatchScore: 1.0
        mapperMismatchPenalty: -0.1
        mapperOffsetShiftPenalty: -0.3
        mapperMinSeedsDistance: 4
        mapperMaxSeedsDistance: 10
        minAlignmentLength: 15
        maxAdjacentIndels: 2
        alignmentStopPenalty: -1000
        absoluteMinScore: 40.0
        relativeMinScore: 0.87
        maxHits: 7
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -9)"
          gapPenalty: -12
    vjAlignmentOrder: VThenJ
    libraryStructure: Unknown
    includeDScore: false
    includeCScore: false
    minSumScore: 120.0
    maxHits: 5
    relativeMinVFR3CDR3Score: 0.7
    allowPartialAlignments: false
    allowNoCDR3PartAlignments: false
    allowChimeras: false
    readsLayout: Opposite
    mergerParameters:
      qualityMergingAlgorithm: MaxSubtraction
      partsLayout: null
      minimalOverlap: 13
      minimalMatchQualitySum: 364
      maxQuality: 50
      minimalIdentity: 0.7
      identityType: MinimalQualityWeighted
    fixSeed: true
    alignmentBoundaryTolerance: 5
    minChimeraDetectionScore: 120
    vjOverlapWindow: 3
    saveOriginalSequence: false
    saveOriginalReads: false
    smartForceEdgeAlignments: true
refineTagsAndSort:
  whitelists: {}
  runCorrection: true
  parameters:
    correctionPower: 0.001
    backgroundSubstitutionRate: 0.001
    backgroundIndelRate: 1.0E-5
    minQuality: 12
    maxSubstitutions: 2
    maxIndels: 2
    maxTotalErrors: 3
    postFilter:
      type: filter_groups
      groupingKeys:
      - allTags:Molecule
      predicates:
      - metrics:
        - type: group_metric_sum_weight
          reportHist:
            log: true
            binNumber: 0
            minBinWidth: 0.2
            multiplyWeightByKey: false
        operator:
          type: group_operator_lowest_threshold
          operators:
          - type: group_operator_advanced_thresholding
            algo:
              type: otsu
            histTransformers:
            - type: inflate
              fraction: 0.15
              value: 1.0
            logX: true
            minimalSample: 20
            fallbackThreshold: 1.0
            accept: High
          - type: group_operator_cumtop
            share: 0.85
            round: Down
            accept: High
          accept: High
        expectedSorting: []
        requiredSequences: []
      expectedSorting:
      - allTags:Molecule
      requiredSequences: []
assemblePartial:
  overlappedOnly: false
  dropPartial: false
  cellLevel: false
  parameters:
    kValue: 12
    kOffset: -7
    minimalAssembleOverlap: 12
    minimalNOverlap: 7
    minimalNOverlapShare: 0.65
    minimalAlignmentMergeIdentity: 0.85
    mergerParameters:
      qualityMergingAlgorithm: SumSubtraction
      partsLayout: CollinearDirect
      minimalOverlap: 20
      minimalMatchQualitySum: 0
      maxQuality: 45
      minimalIdentity: 0.95
      identityType: Unweighted
    maxLeftParts: 256000
    maxLeftMatches: 6144
  command: assemblePartial
extend:
  vAnchor: CDR3Begin
  jAnchor: FR4Begin
  minimalVScore: 50
  minimalJScore: 50
  command: extend
assemble:
  sortBySequence: false
  clnaOutput: false
  cellLevel: false
  consensusAssemblerParameters:
    assembler:
      aAssemblerParameters:
        bandWidth: 4
        scoring:
          type: linear
          alphabet: nucleotide
          subsMatrix: "simple(match = 5, mismatch = -4)"
          gapPenalty: -14
        minAlignmentScore: 40
        maxNormalizedAlignmentPenalty: 0.15
        trimMinimalSumQuality: 0
        trimReferenceRegion: false
        maxQuality: 45
      maxIterations: 6
      minAltSeedQualityScore: 11
      minAltSeedNormalizedPenalty: 0.35
      altSeedPenaltyTolerance: 0.3
      minRecordSharePerConsensus: 0.2
      minRecordsPerConsensus: 0
      minRecursiveRecordShare: 0.4
      minQualityScore: 0
      maxConsensuses: 3
    minTagSuffixShare: 0.0
  cloneAssemblerParameters:
    assemblingFeatures:
    - VDJRegion
    minimalClonalSequenceLength: 12
    qualityAggregationType: Max
    cloneClusteringParameters:
      searchDepth: 2
      allowedMutationsInNRegions: 1
      searchParameters: twoMismatchesOrIndels
      clusteringFilter:
        type: relativeConcentration
        specificMutationProbability: 1.0E-4
    cloneFactoryParameters:
      vParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      jParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      cParameters:
        relativeMinScore: null
        scoring: null
        maxAlignmentWidthLinear: 5
        maxAlignmentWidthAffine: 500
      dParameters:
        relativeMinScore: null
        absoluteMinScore: null
        maxHits: null
        scoring: null
      vdcParameters:
        Variable:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
        Joining:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
        Constant:
          relativeMinScore: null
          scoring: null
          maxAlignmentWidthLinear: 5
          maxAlignmentWidthAffine: 500
    separateByV: true
    separateByJ: true
    separateByC: true
    maximalPreClusteringRatio: 1.0
    preClusteringScoreFilteringRatio: 2.0
    preClusteringCountFilteringRatio: 2.0
    addReadsCountOnClustering: false
    badQualityThreshold: 20
    maxBadPointsPercent: 0.7
    mappingThreshold: 2of5
    minimalQuality: 0
    postFilters: null
  inferMinRecordsPerConsensus: true
  command: assemble
assembleContigs:
  ignoreTags: false
  parameters:
    branchingMinimalQualityShare: 0.1
    branchingMinimalSumQuality: 60
    decisiveBranchingSumQualityThreshold: 120
    alignedSequenceEdgeDelta: 3
    alignmentEdgeRegionSize: 7
    minimalNonEdgePointsFraction: 0.25
    minimalMeanNormalizedQuality: 5.0
    outputMinimalQualityShare: 0.75
    outputMinimalSumQuality: 0
    subCloningRegions: null
    assemblingRegions: null
    postFiltering:
      type: NoFiltering
    trimmingParameters:
      averageQualityThreshold: 10.0
      windowSize: 8
    minimalContigLength: 20
    alignedRegionsOnly: false
    discardAmbiguousNucleotideCalls: false
  command: assembleContigs
exportAlignments:
  chains: ALL
  noHeader: false
  fields:
  - field: -targetSequences
  - field: -targetQualities
  - field: -vHitsWithScore
  - field: -dHitsWithScore
  - field: -jHitsWithScore
  - field: -cHitsWithScore
  - field: -vAlignments
  - field: -dAlignments
  - field: -jAlignments
  - field: -cAlignments
  - field: -allNFeaturesWithMinQuality
  - field: -allAAFeatures
  - field: -defaultAnchorPoints
exportClones:
  splitByTagType: null
  filterOutOfFrames: false
  filterStops: false
  chains: ALL
  noHeader: false
  fields:
  - field: -cloneId
  - field: -readCount
  - field: -readFraction
  - field: -uniqueTagCount
    args:
    - Molecule
  - field: -uniqueTagFraction
    args:
    - Molecule
  - field: -targetSequences
  - field: -targetQualities
  - field: -vHitsWithScore
  - field: -dHitsWithScore
  - field: -jHitsWithScore
  - field: -cHitsWithScore
  - field: -vAlignments
  - field: -dAlignments
  - field: -jAlignments
  - field: -cAlignments
  - field: -allNFeaturesWithMinQuality
  - field: -allAAFeatures
  - field: -defaultAnchorPoints
  splitFilesBy:
  - geneLabel:ReliableChain
  groupClonesBy: []
qc:
  errorOnFailedCheck: false
  checks:
  - type: SuccessfullyAlignedReads
    upper: 0.9
    middle: 0.7
    label: Successfully aligned reads
  - type: OffTargetReads
    upper: 0.2
    middle: 0.1
    label: Off target (non TCR/IG) reads
  - type: ReadsWithNoVOrJHits
    upper: 0.2
    middle: 0.1
    label: Reads with no V or J hits
  - type: ReadsWithNoBarcode
    upper: 0.2
    middle: 0.1
    label: Reads with no barcode
  - type: OverlappedReadsMoreBetter
    upper: 0.95
    middle: 0.9
    label: Overlapped paired-end reads
  - type: OverlappedReadsLessBetter
    upper: 0.95
    middle: 0.9
    label: Overlapped paired-end reads
  - type: ReadsDroppedInTagRefinement
    upper: 0.1
    middle: 0.05
    label: Reads dropped in tags error correction and filtering
  - type: TagArtificialDiversityEliminated
    tag: UMI
    upper: 0.8
    middle: 0.5
    label: UMIs artificial diversity eliminated
  - type: ReadsDroppedInTagCorrection
    tag: UMI
    upper: 0.1
    middle: 0.05
    label: Reads dropped in UMI error correction and whitelist
  - type: ReadsDroppedInTagFiltering
    upper: 0.1
    middle: 0.05
    label: Reads dropped in tags filtering
  - type: TagGroupsWithNoAssemblingFeature
    upper: 0.2
    middle: 0.1
    label: Tag groups with no assembling feature
  - type: TagGroupsWithMultipleConsensuses
    upper: 0.1
    middle: 0.001
    label: Barcode collisions in clonotype assembly
  - type: UnassignedAlignments
    upper: 0.1
    middle: 0.05
    label: Unassigned alignments in clonotype assembly
  - type: ReadsUsedInClonotypes
    upper: 0.9
    middle: 0.8
    label: Reads used in clonotypes
  - type: AlignmentsWithNoAssemblingFeature
    upper: 0.1
    middle: 0.2
    label: Alignments without assembling feature
  - type: AlignmentsDroppedLowQuality
    upper: 0.1
    middle: 0.05
    label: Alignments dropped due to low sequence quality
  - type: AlignmentsClusteredInAssembler
    upper: 0.1
    middle: 0.05
    label: Alignments clustered in PCR error correction
  - type: ClonesClusteredInAssembler
    upper: 0.1
    middle: 0.05
    label: Clonotypes clustered in PCR error correction
  - type: ClonesDroppedInPostFiltering
    upper: 0.1
    middle: 0.05
    label: Clones dropped in post-filtering
  - type: AlignmentsDroppedInPostFiltering
    upper: 0.1
    middle: 0.05
    label: Alignments dropped in clones post-filtering
