name: "Build"

on:
  push:
    tags: [ '*' ]
    branches: [ '*' ]
  schedule:
    - cron: '10 1 * * *'

  workflow_dispatch: { }

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v3
        with:
          version-canonize: false
      - id: context
        uses: milaboratory/github-ci/actions/context@v3

    outputs:
      is-release: ${{ steps.context.outputs.is-release }}

  run:
    needs:
      - init

    uses: milaboratory/github-ci/.github/workflows/java-gradle.yaml@v3
    with:
      # Environment
      java-version: '11'
      product-name: MiXCR
      product-name-slug: 'mixcr'

      # Tests
      test-unit: true
      test-unit-before-tasks: shadowJar
      test-unit-cache: true
      test-unit-cache-paths: |
        ./src/test/resources/sequences/big/**
      test-unit-cache-key: 'tests-sequences-v1'

      test-integration: true
      test-integration-before-tasks: shadowJar
      test-integration-tasks: ''
      test-integration-cache: true
      test-integration-cache-paths: |
        ./src/test/resources/sequences/big/**
      test-integration-cache-key: 'tests-sequences-v1'
      test-integration-python-version: '3.9'

      # Distribution
      dist-archive: ${{ github.event_name != 'schedule' }}
      dist-archive-tasks: distributionZip
      dist-archive-paths: ./distributions/mixcr*.zip
      dist-archive-s3: true
      dist-archive-s3-add-sha: true

      #CDN redirect
      cdn-redirect-s3: true
      cdn-redirect-s3-bucket-path: 'link/software/mixcr'

      dist-docker: true
      dist-docker-tasks: |
        buildDockerImage
        buildIMGTDockerImage
      dist-docker-image-name: mixcr

      # Release configuration
      release-github-draft: true

      # Send notifications
      notify-telegram: true

    secrets:
      env: |
        { "MI_LICENSE": ${{ toJSON(secrets.MI_LICENSE) }} }

      GRADLE_PROPERTIES: |
        miRepoAccessKeyId=${{ secrets.AWS_CI_ACCESS_KEY_ID }}
        miRepoSecretAccessKey= ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

      AWS_KEY_ID: ${{ secrets.AWS_CI_ACCESS_KEY_ID }}
      AWS_KEY_SECRET: ${{ secrets.AWS_CI_SECRET_ACCESS_KEY }}

      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}

