name: "Build"

on:
  push:
    tags: [ '*' ]
    branches: [ '*' ]
  schedule:
    - cron: '10 1 * * *'

  workflow_dispatch: { }

jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - uses: milaboratory/github-ci/actions/context/init@v4-beta
        with:
          version-canonize: false
      - id: context
        uses: milaboratory/github-ci/actions/context@v4-beta

    outputs:
      is-release: ${{ steps.context.outputs.is-release }}

  run:
    needs:
      - init

    uses: milaboratory/github-ci/.github/workflows/java-gradle.yaml@v4-beta
    with:
      # Environment
      java-version: '11'
      product-name: MiXCR
      product-name-slug: 'mixcr'

      # Tests
      test-unit: true
      test-unit-before-tasks: shadowJarAfterObfuscation
      test-unit-cache: true
      test-unit-cache-paths: |
        ./src/test/resources/sequences/big/**
      test-unit-cache-key: 'tests-sequences-v1'

      test-integration: true
      test-integration-before-tasks: shadowJarAfterObfuscation
      test-integration-tasks: ''
      test-integration-cache: true
      test-integration-cache-paths: |
        ./src/test/resources/sequences/big/**
      test-integration-cache-key: 'tests-sequences-v1'
      test-integration-python-version: '3.9'

      test-s3-iam-role-to-assume: 'arn:aws:iam::013783277167:role/milab-euce1-prod-github-oidc-role-mixcr'

      # Lib
      dist-library: true
      dist-library-dev-tasks: publishAllPublicationsToMiprivRepository
      dist-library-release-tasks: publishAllPublicationsToMiprivRepository

      # Distribution
      dist-archive: true
      dist-archive-tasks: distributionZip
      dist-archive-paths: ./distributions/mixcr*.zip
      dist-archive-s3: true
      dist-archive-s3-add-sha: true
      dist-archive-s3-iam-role-to-assume: 'arn:aws:iam::013783277167:role/milab-euce1-prod-github-oidc-role-mixcr'

      # CDN redirect
      cdn-redirect-s3: false
      cdn-redirect-s3-bucket-path: 'link/software/mixcr'
      cdn-redirect-s3-iam-role-to-assume: 'arn:aws:iam::013783277167:role/milab-euce1-prod-github-oidc-role-mixcr'

      dist-docker: true
      dist-docker-tasks: |
        buildDockerImage
        buildIMGTDockerImage
      dist-docker-image-name: mixcr

      # Release configuration
      release-github-draft: true
      release-s3-iam-role-to-assume: 'arn:aws:iam::013783277167:role/milab-euce1-prod-github-oidc-role-mixcr'

      # Send notifications
      notify-telegram: true

    secrets:
      env: |
        { "MI_LICENSE": ${{ toJSON(secrets.MI_LICENSE) }} }

      GRADLE_PROPERTIES: |
        org.gradle.caching=true
      TELEGRAM_NOTIFICATION_TARGET: ${{ secrets.TG_CHANNEL_MIBUILDS }}
      TELEGRAM_API_TOKEN: ${{ secrets.TG_CI_BOT_TOKEN }}
